// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://petdcrgwktmienxogxdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBldGRjcmd3a3RtaWVueG9neGRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTQ3MTcsImV4cCI6MjA2NDUzMDcxN30.8sQX3W64fONf3-rXSox6Kt5ClJYkf2FTZHoq_WSisxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);